truncate table data.attribute_value_change_functions;
truncate table data.attribute_value_fill_functions;
truncate table data.attribute_values;
truncate table data.attribute_values_journal;
truncate table data.attributes cascade;
truncate table data.client_login;
truncate table data.client_login_journal;
truncate table data.deferred_functions;
truncate table data.deferred_functions_journal;
truncate table data.extensions;
truncate table data.log;
truncate table data.login_objects;
truncate table data.login_objects_journal;
truncate table data.logins cascade;
truncate table data.object_objects;
truncate table data.object_objects_journal;
truncate table data.objects cascade;
truncate table data.params;